<a href="https://colab.research.google.com/github/tranthehien091003/ThuchanhToanCC/blob/main/baitaptuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.Tóm tắt một số phép xử lý ma trận của NumPy và Scipy**

In [25]:
from scipy import linalg # Tải gói linalg của scipy vào bộ nhớ (để sử dụng)
import numpy as np 

In [27]:
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])

In [21]:
F = np.eye(3, k=0)

In [22]:
F = np.eye(3, k=-1)

In [23]:
np.linalg.matrix_rank(C)

3

**Giải các loại phương trình tuyến tính:**

In [28]:
linalg.solve(A, b) 

array([[ 1.23725042+8.78150817j,  0.        -0.46768116j,
         0.        +0.18113286j],
       [-0.46833184+0.70592355j,  0.        +5.21447392j,
         0.        +5.97636961j]])

In [29]:
E = np.mat(a).T

In [30]:
linalg.lstsq(F, E)

(array([[2.],
        [3.],
        [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))

**Ma trận phân kỳ:**

Tính ma trận A

In [1]:
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)

temp = A.dot(A) # tính toan lần thứ 1
print(temp)

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]


In [3]:
k= 6
for i in range(k-1):
  temp = temp.dot(A)
  print (temp)
  print('---')

[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---


Tính ma trận B:

In [5]:
B = np.array([ [0,-1], [-1,0]])
print(B)


[[ 0 -1]
 [-1  0]]


In [6]:
temp = B.dot(B) # tính toan lần thứ 1
print(temp)

[[1 0]
 [0 1]]


In [7]:
k= 5
for i in range(k-1):
  temp = temp.dot(B)
  print (temp)
  print('---') 

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


**2.3 Ma trận hội tụ:**

In [8]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C) 

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [9]:
temp = C.dot(C) # tính toan lần thứ 1
print(temp)

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [11]:
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
  print(temp) 

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.33315905e-302 4.67565073e-299]
 [0.00000000e+000 0.00000000e+000 2.33315905e-302]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.16657952e-302 2.34015852e-299]
 [0.00000000e+000 0.00000000e+000 1.16657952e-302]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.83289762e-303 1.17124584e-299]
 [0.00000000e+000 0.00000000e+000 5.83289762e-303]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.91644881e-303 5.86206210e-300]
 [0.00000000e+000 0.00000000e+000 2.91644881e-303]]
[[1.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 1.4582244e-303 2.9339475e-300]
 [0.0000000e+000 0.0000000e+000 1.4582244e-303]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.29112202e-304 1.46843197e-300]
 [0.00000000e+000 0.00000000e+000 7.29112202e-304]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.64556101e-304 

In [12]:
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
  print(temp) 

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[

**2.4 Ma trận markov:**

In [13]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [14]:
MM = M.dot(M) # tính M3
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [17]:
for i in range(100): # tính các M^ khác.
  MM = MM.dot(M)
print (MM) 

[[0.6 0.6]
 [0.4 0.4]]


**3.2 Phân rã ma trận LU:**

In [32]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)

[[1. 0.]
 [0. 1.]]


In [33]:
print (L)

[[1.   0.  ]
 [0.25 1.  ]]


In [34]:
print (U)

[[0.8   0.3  ]
 [0.    0.625]]


In [35]:
L.dot(U)

array([[0.8, 0.3],
       [0.2, 0.7]])

**5.Bài toán ứng dụng 2 – Bài toán loan tin **

In [37]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) 
print(temp) 

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [38]:
temp = temp.dot(A) 
print(temp)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [40]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
  temp = temp.dot(A)
  sumA = sumA + temp
print (temp)
print (sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
